export enum COUNTRY_CODE {
  AUSTRIA = 'AT',
  BELGIUM = 'BE',
  DENMARK = 'DK',
  FINLAND = 'FI',
  FRANCE = 'FR',
  GERMANY = 'DE',
  ICELAND = 'IS',
  ITALY = 'IT',
  MALTA = 'MT',
  NETHERRANDS = 'NL',
  NORWAY = 'NO',
  PORTUGAL = 'PT',
  SPAIN = 'ES',
  SWEDEN = 'SE',
  SWISS = 'CH',
  UK = 'GB',
  BULGARIA = 'BG',
  CZECH = 'CZ',
  HUNGARY = 'HU',
  POLAND = 'PL',
  ROMANIA = 'RO',
  SLOVENIA = 'SI',
  CROATIA = 'HR',
  SLOVAKIA = 'SK',
  CYPRUS = 'CY',
  GREECE = 'GR',
  CANARY_ISLAND = 'IC',
  REUNION = 'RE',
  BOSNIA = 'BA',
  CEUTA = 'XC',
  ESTONIA = 'EE',
  IRELAND = 'IE',
  CANARIA = 'IC',
  LATVIA = 'LV',
  LITHUANIA = 'LT',
  TURKEY = 'TR',
  SERBIA = 'RS',
}

export enum LANGUAGE_CODE {
  ARABIC = 'ar-XA',
  BULGARIAN = 'bg',
  CROATIAN = 'hr',
  CHECH = 'cs',
  DANISH = 'da',
  GERMAN = 'de',
  GREEK = 'dl',
  ENGLISH = 'en',
  ESTONIAN = 'et',
  SPANISH = 'es',
  FINNISH = 'fi',
  FRENCH = 'fr',
  IRISH = 'ga',
  HINDI = 'hi',
  HUNGARIAN = 'hu',
  HEBREW = 'he',
  ITALIAN = 'it',
  JAPANESE = 'ja',
  KOREAN = 'ko',
  LATVIAN = 'lv',
  LITHUANIAN = 'lt',
  DUTCH = 'nl',
  NORWEGIAN = 'no',
  POLISH = 'pl',
  PORTUGUESE = 'pt',
  SWEDISH = 'sv',
  ROMANIAN = 'ro',
  RUSSIAN = 'ru',
  SERBIAN = 'sr-CS',
  SLOVAK = 'sk',
  SLOVENIAN = 'sl',
  THAI = 'th',
  TURKISH = 'tr',
  UKRAINIAN = 'uk-UA',
  CHINESE_S = 'zh-chs',
  CHINESE_T = 'zh-cht',
}

export enum APP_TYPE {
  ELECTRIFIED = 'ELECTRIFIED',
  POWERTRAIN = 'POWERTRAIN',
  CONNECTIVITY = 'CONNECTIVITY',
  TOTAL = 'TOTAL',
}

export enum DEALER_COUNTRY {
  AUSTRIA = 'C11AB',
  BELGIUM = 'C02AA',
  DENMARK = 'C04AA',
  FINLAND = 'C05AD',
  FRANCE = 'C06AB',
  GERMANY = 'C07AB',
  ICELAND = 'C09AA',
  ITALY = 'C11AB',
  MALTA = 'C13AA',
  NETHERRANDS1 = 'C14AB',
  NETHERRANDS2 = 'C14AC',
  NORWAY = 'C15AB',
  PORTUGAL = 'C16AB',
  SPAIN = 'C17AA',
  SWEDEN = 'C18AA',
  SWISS = 'C19AB',
  UK = 'C21AC',
  BULGARIA = 'C23AG',
  CZECH = 'C24AC',
  HUNGARY = 'C26AC',
  POLAND = 'C27AG',
  ROMANIA = 'C28AG',
  SLOVENIA = 'C32AG',
  CROATIA1 = 'C33AA',
  CROATIA2 = 'C33AG',
  SLOVAKIA = 'C50AB',
  CYPRUS = 'D22AB',
  GREECE = 'D27AB',
  CANARY_ISLAND = 'E45AD',
  REUNION = 'E49AA',
}
